[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# html/css completion
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'xhtml', 'php']

# javascript completion
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_i = 1
on_ft = 'javascript'

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_i = 1
on_ft = 'javascript'

# python completion
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_i = 1
on_ft = 'python'
hook_add = '''
  let g:jedi#force_py_version = 3
'''

# php completion
[[plugins]]
repo = 'padawan-php/deoplete-padawan'
on_i = 1
on_ft = 'php'

#tweet vim setting
[[plugins]]
repo = 'basyura/TweetVim'
hook_add = '''
  let g:tweetvim_display_icon = 1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'mattn/favstar-vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = ['vue', 'toml']
hook_source = '''
  let g:precious_enable_switch_CursorMoved_i = {'*': 0}
  let g:precious_enable_switch_CursorHold    = {'*': 0}
	let g:precious_enable_switchers = {
    \	'*':    {'setfiletype': 0},
    \	'toml': {'setfiletype': 1},
    \	'html': {'setfiletype': 1},
    \	'vue':  {'setfiletype': 1},
	\ }
'''
