[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if ='''has('nvim')'''
on_event = 'InsertEnter'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_ignore_case = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#tag#cache_limit_size = 0
  let g:deoplete#max_list = 15
  let g:deoplete#file#enable_buffer_path = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'context_filetype.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# html/css completion
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'xhtml', 'php']

# javascript completion
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
if = '''has('nvim')'''
on_ft = 'javascript'

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_i = 1
on_ft = 'javascript'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

# python completion
[[plugins]]
repo = 'zchee/deoplete-jedi'
if = '''has('nvim')'''
on_ft = 'python'
hook_source = '''
  let g:deoplete#sources#jedi#enable_cache   = 1
  let g:deoplete#sources#jedi#show_docstring = 0
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_i = 1
on_ft = 'python'
hook_add = '''
  let g:jedi#force_py_version = 3
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_i = 1
on_ft = 'python'

# php completion
[[plugins]]
repo = 'padawan-php/deoplete-padawan'
if = '''has('nvim')'''
on_event = 'InsertEnter'
on_ft = 'php'
hook_source = '''
  augroup padawan-setting
    autocmd! FileType php setlocal completeopt-=preview
  augroup END
'''

# rust configuration
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
let g:rustfmt_autosave = 1
'''

#tweet vim setting
[[plugins]]
repo = 'basyura/TweetVim'
hook_add = '''
  let g:tweetvim_display_icon = 1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'mattn/favstar-vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = ['vue', 'toml']
hook_source = '''
  let g:precious_enable_switch_CursorMoved_i = {'*': 0}
  let g:precious_enable_switch_CursorHold    = {'*': 0}
	let g:precious_enable_switchers = {
    \	'*':    {'setfiletype': 0},
    \	'toml': {'setfiletype': 1},
    \	'html': {'setfiletype': 1},
    \	'vue':  {'setfiletype': 1},
	\ }
'''
